<?php

function rss_menu(){
    $items = array();
    $items['admin/config/content/rss'] = array(
        'title' => 'rss',
        'description' => 'rss feeds',
        'page callback' => 'rss_list',
    );

    return $items;

}

function rss_list(){

        $header = array(
            array('data' => t('Name')),
            array('data' => t('URL')),
            array('data' => t('Actions'))
        );
        $rss = db_select('rss', 'n')
            ->fields('n', array('id', 'name', 'url'))
            ->execute()->fetchAll();
        $row = array();
        if ($rss) {
            foreach ($rss as $rss_feed) {
                $actions = array(
                    l(t('edit'), 'admin/config/content/rss/' . $rss_feed->id . '/edit'),
                    l(t('delete'), 'admin/config/content/rss/' . $rss_feed->id . '/delete'),
                );

                $row [] = array(
                    array('data' => $rss_feed->name),
                    array('data' => $rss_feed->url),
                    array('data' => implode(' | ', $actions)),
                );
            }
        }

        return theme('table', array(
            'header' => $header,
            'rows'   => $row,
        ));

}



function rss_block_info(){
    $blocks['rss'] = array(
        'info' => "RSS feeds",
    );
    return $blocks;
}

function load_rss($result = 'item'){
    $rss_url = "http://partners.userland.com/nytRss/nytHomepage.xml";
    $rss = simplexml_load_file($rss_url);
    $data = $rss->channel->$result;
    return $data;
}

function rss_block_view($delta = ''){
    switch ($delta) {
        case 'rss':
            $block['subject'] = load_rss('title');
            $block['content'] = rssblock_view();
            break;
    }
    return $block;
}

function rssblock_view(){
    $res = load_rss();

    for ($i = 0; $i < 5; $i++){
        $item[]=array(
            'title'=> $res[$i]->title,
            'link' => $res[$i]->link,
            'description' => $res[$i]->description,
        );
    }
    return theme('rssblock', array('item'=>$item));
}

function rss_theme(){
    return array(
        'rssblock' => array(
            'template' => 'rssblock',
            'variable' => array('item'=>array()),
        )
    );
}




