<?php

                
function rss_menu(){
    $items = array();



    $items['admin/config/content/rss'] = array(
        'title'            => 'Add rss',
        'page callback'    => 'drupal_get_form',
        'page arguments'   => array('rss_form'),
        'access arguments' => array('administer site configuration'),
        'type'             => MENU_DEFAULT_LOCAL_TASK,

    );


    return $items;

}



function rss_form($form, &$form_state, $rss = null)
{

    $form['url'] = array(
        '#title'         => t('RSS feed url.'),
        '#description'   => t('Insert RSS url'),
        '#type'          => 'textfield',
        '#default_value' => variable_get('rss_url', 0),
        '#required'      => true,
    );

    $form['submit'] = array(
        '#type'  => 'submit',
        '#value' => t('Add'),
    );

    return $form;

}

function rss_form_submit($form, &$form_state)
{
    $rss = array(
        'url' => $form_state['values']['url'],

    );

        variable_set('rss_url', $rss['url']);

        drupal_set_message(t('RSS Feed added!'));


    drupal_goto('admin/config/content/rss');
}

function rss_block_info(){
    $blocks['rss'] = array(
        'info' => "RSS feeds",
    );
    return $blocks;
}

function load_rss($result = 'item'){
    $rss_url = variable_get('rss_url');
    $rss = simplexml_load_file($rss_url);
    $data = $rss->channel->$result;

   return $data;
}

function rss_block_view($delta = ''){
    switch ($delta) {
        case 'rss':
            $block['subject'] = load_rss('title');
            $block['content'] = rssblock_view();
            break;
    }
    return $block;
}

function rssblock_view(){
    $res = load_rss();

    for ($i = 0; $i < 5; $i++){
        $item[]=array(
            'title'       => $res[$i]->title,
            'link'        => $res[$i]->link,
            'description' => $res[$i]->description,
        );
    }
    return theme('rssblock', array('item'=>$item));
}

function rss_theme(){
    return array(
        'rssblock' => array(
            'template' => 'rssblock',
            'variable' => array('item'=>array()),
        )
    );
}




